import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Target, Plus, Trash2, Loader2, Sparkles, Building2, MapPin, Cpu, TrendingUp } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import DashboardLayout from "@/components/DashboardLayout";


export default function IcpBuilder() {
  const [open, setOpen] = useState(false);
  const [aiOpen, setAiOpen] = useState(false);
  const [aiDescription, setAiDescription] = useState("");
  const [form, setForm] = useState({ name: "", industries: "", locations: "", companySizeMin: 10, companySizeMax: 500, revenueRange: "", technologies: "", buyingSignals: "", painPoints: "" });

  const utils = trpc.useUtils();
  const { data: profiles = [], isLoading } = trpc.icpBuilder.list.useQuery();
  const createMutation = trpc.icpBuilder.create.useMutation({
    onSuccess: () => { utils.icpBuilder.list.invalidate(); setOpen(false); setForm({ name: "", industries: "", locations: "", companySizeMin: 10, companySizeMax: 500, revenueRange: "", technologies: "", buyingSignals: "", painPoints: "" }); toast.success("ICP profile created"); },
    onError: (e) => toast.error(e.message),
  });
  const deleteMutation = trpc.icpBuilder.delete.useMutation({
    onSuccess: () => { utils.icpBuilder.list.invalidate(); toast.success("Profile deleted"); },
  });
  const aiMutation = trpc.icpBuilder.aiGenerate.useMutation({
    onSuccess: (data) => {
      setForm({ name: data.name, industries: data.industries, locations: data.locations, companySizeMin: data.companySizeMin, companySizeMax: data.companySizeMax, revenueRange: data.revenueRange, technologies: data.technologies, buyingSignals: data.buyingSignals, painPoints: data.painPoints });
      setAiOpen(false);
      setOpen(true);
      toast.success("ICP generated by AI — review and save");
    },
    onError: (e) => toast.error(e.message),
  });

  return (
    <DashboardLayout>
      <div className="space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2"><Target className="h-6 w-6 text-rose-500" /> ICP Builder</h1>
          <p className="text-muted-foreground mt-1">Build Ideal Customer Profiles to target the right leads</p>
        </div>
        <div className="flex gap-2">
          <Dialog open={aiOpen} onOpenChange={setAiOpen}>
            <DialogTrigger asChild><Button variant="outline"><Sparkles className="h-4 w-4 mr-2" /> AI Generate</Button></DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>AI ICP Generator</DialogTitle>
                <DialogDescription>Describe your ideal customer and AI will build the profile</DialogDescription>
              </DialogHeader>
              <Textarea placeholder="We sell project management software to mid-size tech companies in Europe who are scaling their engineering teams..." value={aiDescription} onChange={(e) => setAiDescription(e.target.value)} rows={4} />
              <DialogFooter>
                <Button onClick={() => aiMutation.mutate({ description: aiDescription })} disabled={aiMutation.isPending || !aiDescription}>
                  {aiMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Sparkles className="h-4 w-4 mr-2" />} Generate ICP
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
          <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild><Button><Plus className="h-4 w-4 mr-2" /> Manual Create</Button></DialogTrigger>
            <DialogContent className="max-w-lg max-h-[80vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>Create ICP Profile</DialogTitle>
              </DialogHeader>
              <div className="space-y-3">
                <div><Label>Profile Name</Label><Input value={form.name} onChange={(e) => setForm(p => ({ ...p, name: e.target.value }))} placeholder="Enterprise SaaS Buyers" /></div>
                <div><Label>Industries (comma-separated)</Label><Input value={form.industries} onChange={(e) => setForm(p => ({ ...p, industries: e.target.value }))} placeholder="SaaS, FinTech, MarTech" /></div>
                <div><Label>Locations (comma-separated)</Label><Input value={form.locations} onChange={(e) => setForm(p => ({ ...p, locations: e.target.value }))} placeholder="USA, UK, Germany" /></div>
                <div className="grid grid-cols-2 gap-3">
                  <div><Label>Min Company Size</Label><Input type="number" value={form.companySizeMin} onChange={(e) => setForm(p => ({ ...p, companySizeMin: parseInt(e.target.value) || 0 }))} /></div>
                  <div><Label>Max Company Size</Label><Input type="number" value={form.companySizeMax} onChange={(e) => setForm(p => ({ ...p, companySizeMax: parseInt(e.target.value) || 0 }))} /></div>
                </div>
                <div><Label>Revenue Range</Label><Input value={form.revenueRange} onChange={(e) => setForm(p => ({ ...p, revenueRange: e.target.value }))} placeholder="$1M-$50M" /></div>
                <div><Label>Technologies</Label><Input value={form.technologies} onChange={(e) => setForm(p => ({ ...p, technologies: e.target.value }))} placeholder="React, AWS, Salesforce" /></div>
                <div><Label>Buying Signals</Label><Input value={form.buyingSignals} onChange={(e) => setForm(p => ({ ...p, buyingSignals: e.target.value }))} placeholder="Hiring, Funding round, New office" /></div>
                <div><Label>Pain Points</Label><Input value={form.painPoints} onChange={(e) => setForm(p => ({ ...p, painPoints: e.target.value }))} placeholder="Manual processes, Scaling issues" /></div>
              </div>
              <DialogFooter>
                <Button onClick={() => createMutation.mutate(form)} disabled={createMutation.isPending || !form.name || !form.industries || !form.locations}>
                  {createMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : null} Create Profile
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {isLoading ? (
        <div className="flex justify-center py-12"><Loader2 className="h-8 w-8 animate-spin text-muted-foreground" /></div>
      ) : profiles.length === 0 ? (
        <Card><CardContent className="py-12 text-center"><Target className="h-12 w-12 mx-auto text-muted-foreground mb-4" /><p className="text-lg font-medium">No ICP profiles yet</p><p className="text-muted-foreground">Use AI or manually create your ideal customer profile</p></CardContent></Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {profiles.map((p) => (
            <Card key={p.id}>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-lg">{p.name}</CardTitle>
                  <div className="flex items-center gap-2">
                    {p.isDefault && <Badge>Default</Badge>}
                    <Badge variant="secondary">{p.matchedLeads} matches</Badge>
                    <Button variant="ghost" size="icon" onClick={() => deleteMutation.mutate({ id: p.id })}><Trash2 className="h-4 w-4 text-destructive" /></Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex flex-wrap gap-2">
                  <div className="flex items-center gap-1 text-sm"><Building2 className="h-3 w-3" /> {p.industries}</div>
                </div>
                <div className="flex flex-wrap gap-2">
                  <div className="flex items-center gap-1 text-sm"><MapPin className="h-3 w-3" /> {p.locations}</div>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="outline">{p.companySizeMin}-{p.companySizeMax} employees</Badge>
                  {p.revenueRange && <Badge variant="outline">{p.revenueRange}</Badge>}
                </div>
                {p.technologies && <div className="flex items-center gap-1 text-sm text-muted-foreground"><Cpu className="h-3 w-3" /> {p.technologies}</div>}
                {p.buyingSignals && <div className="flex items-center gap-1 text-sm text-muted-foreground"><TrendingUp className="h-3 w-3" /> {p.buyingSignals}</div>}
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
    </DashboardLayout>
  );
}
