/**
 * Mock Signal Provider — Level 1 / Level 2 Fallback
 * Returns static fixture data. Always available, no API key required.
 */
import type { SignalProvider } from "./index";
import type { GlobalSignal } from "../../shared/globalSignals";

const now = Date.now();
const h = (hours: number) => now - hours * 3_600_000;

const SERVER_MOCK_SIGNALS: GlobalSignal[] = [
    {
        id: "mock-io-001",
        title: "Major BGP Route Leak — Central European ISPs",
        summary: "A BGP misconfiguration at AS12345 caused route propagation errors affecting multiple ISPs across Czech Republic, Slovakia and Austria. Packet loss reported at 18-40%.",
        category: "internet_outage", severity: "high", confidence: 87, status: "confirmed",
        region: "Central Europe", country: "CZ", lat: 50.08, lon: 14.44,
        detectedAt: h(2), updatedAt: h(0.5),
        sourceName: "Cloudflare Radar", sourceUrl: "https://radar.cloudflare.com",
        rawProvider: "mock", tags: ["bgp", "routing", "isp", "central-europe"],
        affectedSystems: ["AS12345", "AS5568", "T-Mobile CZ"],
    },
    {
        id: "mock-io-002",
        title: "AWS us-east-1 Partial Degradation",
        summary: "Amazon Web Services reported degraded performance for EC2, RDS and Lambda in us-east-1. Major SaaS platforms reporting elevated error rates.",
        category: "internet_outage", severity: "medium", confidence: 95, status: "confirmed",
        region: "North America", country: "US", lat: 39.05, lon: -77.49,
        detectedAt: h(4), updatedAt: h(1),
        sourceName: "AWS Health Dashboard", sourceUrl: "https://health.aws.amazon.com",
        rawProvider: "mock", tags: ["aws", "cloud", "us-east-1"],
        affectedSystems: ["EC2", "RDS", "Lambda"],
    },
    {
        id: "mock-ct-001",
        title: "Ransomware Campaign Targeting DACH Healthcare",
        summary: "BlackCat/ALPHV variant targeting hospital systems in Germany, Austria and Switzerland. 3 confirmed incidents. CISA advisory issued.",
        category: "cyber_threat", severity: "critical", confidence: 91, status: "confirmed",
        region: "DACH", country: "DE", lat: 52.52, lon: 13.40,
        detectedAt: h(6), updatedAt: h(0.3),
        sourceName: "AlienVault OTX", sourceUrl: "https://otx.alienvault.com",
        rawProvider: "mock", tags: ["ransomware", "healthcare", "dach"],
        affectedSystems: ["Hospital EHR", "PACS systems"], mitreAttackId: "T1486",
    },
    {
        id: "mock-ct-002",
        title: "DDoS Attack — Czech Financial Sector",
        summary: "Coordinated volumetric DDoS attack (~420 Gbps peak) targeting online banking portals. Killnet claimed responsibility.",
        category: "cyber_threat", severity: "high", confidence: 78, status: "likely",
        region: "Czech Republic", country: "CZ", lat: 50.08, lon: 14.44,
        detectedAt: h(1), updatedAt: h(0.2),
        sourceName: "NÚKIB", sourceUrl: "https://www.nukib.cz",
        rawProvider: "mock", tags: ["ddos", "banking", "finance", "killnet"],
        mitreAttackId: "T1498",
    },
    {
        id: "mock-ct-003",
        title: "Zero-Day in Ivanti Connect Secure Exploited",
        summary: "Authentication bypass in Ivanti VPN gateway actively exploited. Threat actors establishing persistent backdoors. Patch available.",
        category: "cyber_threat", severity: "critical", confidence: 96, status: "confirmed",
        region: "Global", detectedAt: h(18), updatedAt: h(3),
        sourceName: "abuse.ch", sourceUrl: "https://abuse.ch",
        rawProvider: "mock", tags: ["zero-day", "ivanti", "vpn"],
        mitreAttackId: "T1190",
    },
    {
        id: "mock-nd-001",
        title: "M6.4 Earthquake — Northern Italy",
        summary: "Magnitude 6.4 earthquake struck 40km north of Milan. Infrastructure damage reported.",
        category: "natural_disaster", severity: "high", confidence: 99, status: "confirmed",
        region: "Southern Europe", country: "IT", lat: 45.46, lon: 9.19,
        detectedAt: h(3), updatedAt: h(1.5),
        sourceName: "USGS Earthquake Hazards", sourceUrl: "https://earthquake.usgs.gov",
        rawProvider: "mock", tags: ["earthquake", "italy"],
    },
    {
        id: "mock-nd-002",
        title: "Wildfire — Southern France, Provence",
        summary: "Active wildfire burning 12,000+ hectares. Three data centers in proximity evacuated. Fiber routes disrupted.",
        category: "natural_disaster", severity: "medium", confidence: 88, status: "confirmed",
        region: "Western Europe", country: "FR", lat: 43.53, lon: 5.45,
        detectedAt: h(8), updatedAt: h(2),
        sourceName: "NASA FIRMS", sourceUrl: "https://firms.modaps.eosdis.nasa.gov",
        rawProvider: "mock", tags: ["wildfire", "france", "datacenter-risk"],
    },
    {
        id: "mock-infra-001",
        title: "DE-CIX Frankfurt — Planned Maintenance",
        summary: "Maintenance on DE-CIX Frankfurt core switching fabric. 4-hour window. Traffic rerouted via Amsterdam IX.",
        category: "infrastructure", severity: "low", confidence: 100, status: "confirmed",
        region: "Germany", country: "DE", lat: 50.11, lon: 8.68,
        detectedAt: h(0), updatedAt: h(0),
        sourceName: "DE-CIX Status", sourceUrl: "https://status.de-cix.net",
        rawProvider: "mock", tags: ["ix", "frankfurt", "maintenance"],
    },
    {
        id: "mock-infra-002",
        title: "Power Grid Vulnerability — Polish Transmission System",
        summary: "ENISA advisory: identified vulnerabilities in SCADA systems managing Polish HV grid. Unverified OSINT suggests nation-state reconnaissance.",
        category: "infrastructure", severity: "high", confidence: 52, status: "unverified",
        region: "Eastern Europe", country: "PL", lat: 52.23, lon: 21.01,
        detectedAt: h(12), updatedAt: h(6),
        sourceName: "ENISA Threat Landscape", sourceUrl: "https://www.enisa.europa.eu",
        rawProvider: "mock", tags: ["scada", "power-grid", "poland", "osint"],
    },
    {
        id: "mock-cable-001",
        title: "MAREA Cable — Partial Capacity Loss",
        summary: "Microsoft-Facebook MAREA transatlantic cable reporting 35% capacity reduction on Segment 3. Traffic rerouted.",
        category: "cables", severity: "medium", confidence: 72, status: "likely",
        region: "North Atlantic", country: "ES", lat: 43.26, lon: -2.93,
        detectedAt: h(24), updatedAt: h(10),
        sourceName: "TeleGeography", sourceUrl: "https://www.submarinecablemap.com",
        rawProvider: "mock", tags: ["submarine-cable", "marea", "transatlantic"],
        affectedSystems: ["MAREA Cable Seg-3"],
    },
    {
        id: "mock-cable-002",
        title: "Red Sea Cable Disruptions — Ongoing",
        summary: "AAE-1, SeaMeWe-5 and EIG cables showing faults. Middle East traffic latency elevated +40-60ms.",
        category: "cables", severity: "critical", confidence: 83, status: "confirmed",
        region: "Middle East", lat: 15.55, lon: 42.58,
        detectedAt: h(72), updatedAt: h(4),
        sourceName: "ISCPC Cable Status", sourceUrl: "https://www.submarinecablemap.com",
        rawProvider: "mock", tags: ["red-sea", "cables", "geopolitical"],
        affectedSystems: ["AAE-1", "SeaMeWe-5", "EIG"],
    },
    {
        id: "mock-dc-001",
        title: "Cooling Failure — Equinix AM7 Amsterdam",
        summary: "Partial cooling failure in Equinix AM7. 12 cabinets powered down for thermal protection. Estimated resolution: 6h.",
        category: "datacenter", severity: "high", confidence: 90, status: "confirmed",
        region: "Netherlands", country: "NL", lat: 52.38, lon: 4.90,
        detectedAt: h(1.5), updatedAt: h(0.3),
        sourceName: "Equinix Status", sourceUrl: "https://status.equinix.com",
        rawProvider: "mock", tags: ["datacenter", "cooling", "equinix"],
    },
    {
        id: "mock-dc-002",
        title: "Google Cloud europe-west3 — Storage API Slowdown",
        summary: "Elevated latency on Cloud Storage API in Frankfurt. Object reads 3-8× slower. GKE workloads with persistent volumes affected.",
        category: "datacenter", severity: "medium", confidence: 94, status: "confirmed",
        region: "Germany", country: "DE", lat: 50.11, lon: 8.68,
        detectedAt: h(0.7), updatedAt: h(0.1),
        sourceName: "Google Cloud Status", sourceUrl: "https://status.cloud.google.com",
        rawProvider: "mock", tags: ["gcp", "storage", "frankfurt"],
        affectedSystems: ["Cloud Storage", "GKE"],
    },
    {
        id: "mock-sw-001",
        title: "X2.3 Solar Flare — GPS and HF Radio Disruption",
        summary: "Major X-class solar flare recorded. R3-class radio blackout on sunlit hemisphere. GPS positioning accuracy degraded by 2-5m.",
        category: "space_weather", severity: "high", confidence: 99, status: "confirmed",
        region: "Global — Sunlit Hemisphere",
        detectedAt: h(5), updatedAt: h(2),
        sourceName: "NOAA Space Weather Prediction Center", sourceUrl: "https://www.swpc.noaa.gov",
        rawProvider: "mock", tags: ["solar-flare", "gps", "r3-blackout"],
        affectedSystems: ["GPS L1/L2", "HF Aviation Radio"],
    },
    {
        id: "mock-sw-002",
        title: "Kp-7 Geomagnetic Storm — Pipeline & Grid Risk",
        summary: "Severe geomagnetic storm (Kp=7) in progress. GIC risk for high-latitude power grids and pipelines. Aurora visible to 50°N.",
        category: "space_weather", severity: "medium", confidence: 85, status: "confirmed",
        region: "High Latitudes",
        detectedAt: h(3), updatedAt: h(0.8),
        sourceName: "ESA Space Weather Service", sourceUrl: "https://swe.ssa.esa.int",
        rawProvider: "mock", tags: ["geomagnetic-storm", "kp7", "gic"],
        affectedSystems: ["HV Power Grids", "Natural Gas Pipelines"],
    },
];

export const mockProvider: SignalProvider = {
    name: "Mock Data (Demo)",
    slug: "mock",
    isConfigured: () => true,
    fetchSignals: async () => SERVER_MOCK_SIGNALS,
};
