/**
 * Global Signal Desk — Mock Data Fixture
 * 15 signals across all 7 categories
 * Used as fallback when no API key is configured (Level 1 / Level 2 fallback)
 */
import type { GlobalSignal } from "./types";

const now = Date.now();
const h = (hours: number) => now - hours * 3600_000;

export const MOCK_SIGNALS: GlobalSignal[] = [
    // ── INTERNET OUTAGES ──────────────────────────────────────────────
    {
        id: "mock-io-001",
        title: "Major BGP Route Leak — Central European ISPs",
        summary: "A BGP misconfiguration at AS12345 caused route propagation errors affecting multiple ISPs across Czech Republic, Slovakia and Austria. Packet loss reported at 18-40% for affected networks.",
        category: "internet_outage",
        severity: "high",
        confidence: 87,
        status: "confirmed",
        region: "Central Europe",
        country: "CZ",
        lat: 50.08,
        lon: 14.44,
        detectedAt: h(2),
        updatedAt: h(0.5),
        sourceName: "Cloudflare Radar",
        sourceUrl: "https://radar.cloudflare.com",
        rawProvider: "cloudflare_radar_mock",
        tags: ["bgp", "routing", "isp", "central-europe"],
        affectedSystems: ["AS12345", "AS5568", "T-Mobile CZ"],
    },
    {
        id: "mock-io-002",
        title: "AWS us-east-1 Partial Degradation",
        summary: "Amazon Web Services reported degraded performance for EC2, RDS and Lambda functions in us-east-1 region. Major SaaS platforms reporting elevated error rates.",
        category: "internet_outage",
        severity: "medium",
        confidence: 95,
        status: "confirmed",
        region: "North America",
        country: "US",
        lat: 39.05,
        lon: -77.49,
        detectedAt: h(4),
        updatedAt: h(1),
        sourceName: "AWS Health Dashboard",
        sourceUrl: "https://health.aws.amazon.com",
        rawProvider: "aws_health_mock",
        tags: ["aws", "cloud", "us-east-1", "ec2"],
        affectedSystems: ["EC2", "RDS", "Lambda", "CloudFront"],
    },

    // ── CYBER THREATS ─────────────────────────────────────────────────
    {
        id: "mock-ct-001",
        title: "Ransomware Campaign Targeting DACH Healthcare",
        summary: "BlackCat/ALPHV variant targeting hospital systems in Germany, Austria and Switzerland. 3 confirmed incidents. Initial vector: phishing via VPN credential harvesting. CISA advisory issued.",
        category: "cyber_threat",
        severity: "critical",
        confidence: 91,
        status: "confirmed",
        region: "DACH",
        country: "DE",
        lat: 52.52,
        lon: 13.40,
        detectedAt: h(6),
        updatedAt: h(0.3),
        sourceName: "AlienVault OTX",
        sourceUrl: "https://otx.alienvault.com",
        rawProvider: "alienvault_mock",
        tags: ["ransomware", "healthcare", "dach", "blackcat", "alphv"],
        affectedSystems: ["Hospital EHR", "PACS systems"],
        mitreAttackId: "T1486",
    },
    {
        id: "mock-ct-002",
        title: "DDoS Attack — Czech Financial Sector",
        summary: "Coordinated volumetric DDoS attack (estimated 420 Gbps peak) targeting online banking portals of major Czech banks. Skupiny Killnet se přihlásily k odpovědnosti.",
        category: "cyber_threat",
        severity: "high",
        confidence: 78,
        status: "likely",
        region: "Czech Republic",
        country: "CZ",
        lat: 50.08,
        lon: 14.44,
        detectedAt: h(1),
        updatedAt: h(0.2),
        sourceName: "NÚKIB",
        sourceUrl: "https://www.nukib.cz",
        rawProvider: "nukib_mock",
        tags: ["ddos", "banking", "finance", "killnet", "czechia"],
        affectedSystems: ["Online Banking", "Payment APIs"],
        mitreAttackId: "T1498",
    },
    {
        id: "mock-ct-003",
        title: "Zero-Day in Ivanti Connect Secure Exploited in Wild",
        summary: "CVE-2025-XXXX actively exploited. Authentication bypass in Ivanti VPN gateway. Threat actors establishing persistent backdoors. Patch available but widespread exposure remains.",
        category: "cyber_threat",
        severity: "critical",
        confidence: 96,
        status: "confirmed",
        region: "Global",
        detectedAt: h(18),
        updatedAt: h(3),
        sourceName: "abuse.ch",
        sourceUrl: "https://abuse.ch",
        rawProvider: "abuse_ch_mock",
        tags: ["zero-day", "ivanti", "vpn", "cve", "exploit"],
        affectedSystems: ["Ivanti Connect Secure", "VPN Gateways"],
        mitreAttackId: "T1190",
    },

    // ── NATURAL DISASTERS ─────────────────────────────────────────────
    {
        id: "mock-nd-001",
        title: "M6.4 Earthquake — Northern Italy",
        summary: "Magnitude 6.4 earthquake struck 40km north of Milan. Tremors felt across northern Italy and southern Switzerland. Infrastructure damage reported. No casualties confirmed yet.",
        category: "natural_disaster",
        severity: "high",
        confidence: 99,
        status: "confirmed",
        region: "Southern Europe",
        country: "IT",
        lat: 45.46,
        lon: 9.19,
        detectedAt: h(3),
        updatedAt: h(1.5),
        sourceName: "USGS Earthquake Hazards",
        sourceUrl: "https://earthquake.usgs.gov",
        rawProvider: "usgs_mock",
        tags: ["earthquake", "italy", "infrastructure", "m6"],
    },
    {
        id: "mock-nd-002",
        title: "Wildfire — Southern France, Provence Region",
        summary: "Active wildfire complex burning 12,000+ hectares in Provence. Three data centers in proximity evacuated. Fiber routes disrupted in Aix-en-Provence area.",
        category: "natural_disaster",
        severity: "medium",
        confidence: 88,
        status: "confirmed",
        region: "Western Europe",
        country: "FR",
        lat: 43.53,
        lon: 5.45,
        detectedAt: h(8),
        updatedAt: h(2),
        sourceName: "NASA FIRMS",
        sourceUrl: "https://firms.modaps.eosdis.nasa.gov",
        rawProvider: "nasa_firms_mock",
        tags: ["wildfire", "france", "provence", "datacenter-risk"],
    },

    // ── INFRASTRUCTURE ────────────────────────────────────────────────
    {
        id: "mock-infra-001",
        title: "Frankfurt Internet Exchange (DE-CIX) — Maintenance Window",
        summary: "Planned maintenance on DE-CIX Frankfurt core switching fabric. 4-hour window affecting peak traffic routing for European ISPs. Traffic rerouted via Amsterdam IX.",
        category: "infrastructure",
        severity: "low",
        confidence: 100,
        status: "confirmed",
        region: "Germany",
        country: "DE",
        lat: 50.11,
        lon: 8.68,
        detectedAt: h(0),
        updatedAt: h(0),
        sourceName: "DE-CIX Status",
        sourceUrl: "https://status.de-cix.net",
        rawProvider: "de_cix_mock",
        tags: ["ix", "frankfurt", "maintenance", "routing"],
        affectedSystems: ["DE-CIX Frankfurt", "Peering fabric"],
    },
    {
        id: "mock-infra-002",
        title: "Power Grid Vulnerability — Polish Transmission System",
        summary: "ENISA advisory: identified vulnerabilities in SCADA systems managing Polish high-voltage grid. Unverified OSINT suggests nation-state reconnaissance activity.",
        category: "infrastructure",
        severity: "high",
        confidence: 52,
        status: "unverified",
        region: "Eastern Europe",
        country: "PL",
        lat: 52.23,
        lon: 21.01,
        detectedAt: h(12),
        updatedAt: h(6),
        sourceName: "ENISA Threat Landscape",
        sourceUrl: "https://www.enisa.europa.eu/topics/threat-risk-management",
        rawProvider: "enisa_mock",
        tags: ["scada", "power-grid", "ics-ot", "poland", "osint"],
        affectedSystems: ["SCADA / ICS", "HV Transmission"],
    },

    // ── SUBMARINE CABLES ──────────────────────────────────────────────
    {
        id: "mock-cable-001",
        title: "MAREA Cable — Partial Capacity Loss",
        summary: "Microsoft-Facebook MAREA transatlantic cable reporting 35% capacity reduction on Segment 3 (Bilbao touchdown). Cause: suspected dragger vessel damage. Traffic rerouted to AEConnect-1 and TAT-14.",
        category: "cables",
        severity: "medium",
        confidence: 72,
        status: "likely",
        region: "North Atlantic",
        country: "ES",
        lat: 43.26,
        lon: -2.93,
        detectedAt: h(24),
        updatedAt: h(10),
        sourceName: "TeleGeography Cable Map",
        sourceUrl: "https://www.submarinecablemap.com",
        rawProvider: "telegeography_mock",
        tags: ["submarine-cable", "marea", "transatlantic", "microsoft", "facebook"],
        affectedSystems: ["MAREA Cable Seg-3"],
    },
    {
        id: "mock-cable-002",
        title: "Red Sea Cable Disruptions — Ongoing",
        summary: "Houthi activity continues to threaten cable infrastructure in Red Sea. AAE-1, SeaMeWe-5 and EIG cables showing intermittent faults. Middle East traffic latency elevated +40-60ms.",
        category: "cables",
        severity: "critical",
        confidence: 83,
        status: "confirmed",
        region: "Middle East",
        lat: 15.55,
        lon: 42.58,
        detectedAt: h(72),
        updatedAt: h(4),
        sourceName: "ISCPC Cable Status",
        sourceUrl: "https://www.submarinecablemap.com",
        rawProvider: "iscpc_mock",
        tags: ["red-sea", "cables", "aae-1", "geopolitical", "houthi"],
        affectedSystems: ["AAE-1", "SeaMeWe-5", "EIG"],
    },

    // ── DATACENTERS ───────────────────────────────────────────────────
    {
        id: "mock-dc-001",
        title: "Cooling Failure — Equinix AM7 Amsterdam",
        summary: "Partial cooling system failure in Equinix AM7 (Amsterdam). 12 cabinets powered down for thermal protection. Customers notified. Estimated resolution: 6h.",
        category: "datacenter",
        severity: "high",
        confidence: 90,
        status: "confirmed",
        region: "Netherlands",
        country: "NL",
        lat: 52.38,
        lon: 4.90,
        detectedAt: h(1.5),
        updatedAt: h(0.3),
        sourceName: "Equinix Status",
        sourceUrl: "https://status.equinix.com",
        rawProvider: "equinix_status_mock",
        tags: ["datacenter", "cooling", "equinix", "amsterdam"],
        affectedSystems: ["AM7 Colo", "Cross-connects"],
    },
    {
        id: "mock-dc-002",
        title: "Google Cloud europe-west3 — Storage API Slowdown",
        summary: "Elevated latency on Cloud Storage API in europe-west3 (Frankfurt). Object read operations 3-8× slower than baseline. GKE workloads with persistent volumes affected.",
        category: "datacenter",
        severity: "medium",
        confidence: 94,
        status: "confirmed",
        region: "Germany",
        country: "DE",
        lat: 50.11,
        lon: 8.68,
        detectedAt: h(0.7),
        updatedAt: h(0.1),
        sourceName: "Google Cloud Status",
        sourceUrl: "https://status.cloud.google.com",
        rawProvider: "gcp_status_mock",
        tags: ["gcp", "google-cloud", "storage", "frankfurt", "europe-west3"],
        affectedSystems: ["Cloud Storage", "GKE", "BigQuery"],
    },

    // ── SPACE / WEATHER ───────────────────────────────────────────────
    {
        id: "mock-sw-001",
        title: "X2.3 Solar Flare — GPS and HF Radio Disruption",
        summary: "Major X-class solar flare (X2.3) recorded at 08:14 UTC. R3-class radio blackout on sunlit Earth hemisphere. GPS positioning accuracy degraded by 2-5m. Satellite operators notified.",
        category: "space_weather",
        severity: "high",
        confidence: 99,
        status: "confirmed",
        region: "Global — Sunlit Hemisphere",
        detectedAt: h(5),
        updatedAt: h(2),
        sourceName: "NOAA Space Weather Prediction Center",
        sourceUrl: "https://www.swpc.noaa.gov",
        rawProvider: "noaa_swpc_mock",
        tags: ["solar-flare", "x-class", "gps", "hf-radio", "r3-blackout"],
        affectedSystems: ["GPS L1/L2", "HF Aviation Radio", "LEO Satellites"],
    },
    {
        id: "mock-sw-002",
        title: "Kp-7 Geomagnetic Storm — Pipeline & Grid Risk",
        summary: "Severe geomagnetic storm (Kp=7) in progress. Geomagnetically induced currents (GIC) risk for high-latitude power grids and natural gas pipelines. Aurora visible to 50°N latitude.",
        category: "space_weather",
        severity: "medium",
        confidence: 85,
        status: "confirmed",
        region: "High Latitudes",
        detectedAt: h(3),
        updatedAt: h(0.8),
        sourceName: "ESA Space Weather Service",
        sourceUrl: "https://swe.ssa.esa.int",
        rawProvider: "esa_sws_mock",
        tags: ["geomagnetic-storm", "kp7", "gic", "power-grid", "pipeline"],
        affectedSystems: ["HV Power Grids", "Natural Gas Pipelines", "LEO Satellites"],
    },
];

export const MOCK_LAST_UPDATED = Date.now();
export const MOCK_SIGNAL_COUNT = MOCK_SIGNALS.length;
export const MOCK_CRITICAL_COUNT = MOCK_SIGNALS.filter(s => s.severity === "critical").length;
